Q 1->3

In [1]:
import sklearn
from sklearn.neighbors import KNeighborsClassifier
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np
import pandas as pd

corpus = ["ai is powerful and useful",
          "smart and adaptive system",
          "very smart and useful",
          "learning AI is very hard",
          "ai can be biased",
          "biased and flawed"]

y_data = np.array([1, 1, 1, 0, 0, 0])

vectorizer = CountVectorizer()

X_data = vectorizer.fit_transform(corpus)

text = "ai is a smart system"
X_text = vectorizer.transform([text])
X_text.toarray()

array([[0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0]])

In [2]:
word_to_idx = vectorizer.vocabulary_
print(word_to_idx)
display(
    f"Bộ từ vựng xây dựng từ corpus: {dict(sorted(vectorizer.vocabulary_.items()))}")

{'ai': 1, 'is': 8, 'powerful': 10, 'and': 2, 'useful': 13, 'smart': 11, 'adaptive': 0, 'system': 12, 'very': 14, 'learning': 9, 'hard': 7, 'can': 5, 'be': 3, 'biased': 4, 'flawed': 6}


"Bộ từ vựng xây dựng từ corpus: {'adaptive': 0, 'ai': 1, 'and': 2, 'be': 3, 'biased': 4, 'can': 5, 'flawed': 6, 'hard': 7, 'is': 8, 'learning': 9, 'powerful': 10, 'smart': 11, 'system': 12, 'useful': 13, 'very': 14}"

In [3]:
text2 = "learning AI is very hard"
X_text2 = vectorizer.transform([text2])
X_text2.toarray()

def euclidean_distance(x1, x2):
    return np.sqrt(np.sum((x1 - x2) ** 2))

euclid_dist = np.linalg.norm(X_text.toarray() - X_text2.toarray())
euclid_dist2 = euclidean_distance(X_text.toarray(), X_text2.toarray())
print(f"Euclidean distance: {euclid_dist:2f}")
print(f"Euclidean distance2: {euclid_dist2:2f}")


Euclidean distance: 2.236068
Euclidean distance2: 2.236068


In [4]:
from sklearn.metrics.pairwise import cosine_similarity

def top_3_similar_to_text(X_text, X_data, corpus):
    # Tính cosine similarity giữa câu query và tất cả câu trong corpus
    similarities = cosine_similarity(X_text, X_data)[0]
    print(f'similarities: {similarities}')
    # Lấy ra 3 index có similarity cao nhất
    top_3_indices = similarities.argsort()[-3:][::-1]

    # Trả về 3 câu tương ứng từ corpus
    return [corpus[i] for i in top_3_indices]


X_text = vectorizer.transform(["ai is a smart system"])
result = top_3_similar_to_text(X_text, X_data, corpus)
print("Top 3 câu tương tự nhất:")
for i, sentence in enumerate(result, 1):
    print(f"{i}. {sentence}")

similarities: [0.4472136 0.5       0.25      0.4472136 0.25      0.       ]
Top 3 câu tương tự nhất:
1. smart and adaptive system
2. learning AI is very hard
3. ai is powerful and useful


In [5]:
# Q8
C1 = [0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0]  # ai is powerful and useful
for i in [1, 2, 3, 5]:
    print(X_data.toarray()[i])
    dist = np.linalg.norm(C1 - X_data.toarray()[i])
    print(f'Distance: {dist}')




[1 0 1 0 0 0 0 0 0 0 0 1 1 0 0]
Distance: 2.6457513110645907
[0 0 1 0 0 0 0 0 0 0 0 1 0 1 1]
Distance: 2.23606797749979
[0 1 0 0 0 0 0 1 1 1 0 0 0 0 1]
Distance: 2.449489742783178
[0 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Distance: 2.449489742783178


In [6]:
# Q9
C2 = [0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
for i in [1, 2, 3, 5]:
    print(X_data.toarray()[i])
    dist = np.linalg.norm(C2 - X_data.toarray()[i])
    print(f'Distance: {dist}')

[1 0 1 0 0 0 0 0 0 0 0 1 1 0 0]
Distance: 2.8284271247461903
[0 0 1 0 0 0 0 0 0 0 0 1 0 1 1]
Distance: 2.8284271247461903
[0 1 0 0 0 0 0 1 1 1 0 0 0 0 1]
Distance: 2.6457513110645907
[0 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Distance: 2.23606797749979


In [7]:
# Q10
allocation = []

for vec in X_data.toarray():
    dist1 = np.linalg.norm(C1 - vec)
    dist2 = np.linalg.norm(C2 - vec)
    if dist1 < dist2:
        allocation.append('C1')
    else:
        allocation.append('C2')

print(f'Allocation: {allocation}')


Allocation: ['C1', 'C1', 'C1', 'C1', 'C2', 'C2']


In [8]:
# Q11: Cập nhật lại tọa độ tâm cụm mới của C1 và C2
C1_points = []
C2_points = []

for i in range(len(X_data.toarray())):
    if allocation[i] == 'C1':
        C1_points.append(X_data.toarray()[i])
    else:
        C2_points.append(X_data.toarray()[i])
        
C1_points = np.array(C1_points)
C2_points = np.array(C2_points)

C1_new = np.mean(C1_points, axis=0) if len(
    C1_points) > 0 else np.zeros_like(C1)
C2_new = np.mean(C2_points, axis=0) if len(
    C2_points) > 0 else np.zeros_like(C2)

print("Tọa độ tâm cụm mới C1:", C1_new)
print("Tọa độ tâm cụm mới C2:", C2_new)
        

Tọa độ tâm cụm mới C1: [0.25 0.5  0.75 0.   0.   0.   0.   0.25 0.5  0.25 0.25 0.5  0.25 0.5
 0.5 ]
Tọa độ tâm cụm mới C2: [0.  0.5 0.5 0.5 1.  0.5 0.5 0.  0.  0.  0.  0.  0.  0.  0. ]


In [9]:
# Q12
allocation = []

for vec in X_data.toarray():
    dist1 = np.linalg.norm(C1_new - vec)
    dist2 = np.linalg.norm(C2_new - vec)
    if dist1 < dist2:
        allocation.append('C1')
    else:
        allocation.append('C2')

print(f'Allocation: {allocation}')

Allocation: ['C1', 'C1', 'C1', 'C1', 'C2', 'C2']


Q 4 -> 7

In [10]:
!mkdir data
%cd data

!gdown 1dLF8lffQLgBO5Thu__Lk5Pbw57fTkncc

%cd ..

d:\AIVietNam\2024\aio-2024-hw\tests\final\23_05_2025_test1\data


A subdirectory or file data already exists.


d:\AIVietNam\2024\aio-2024-hw\tests\final\23_05_2025_test1


Downloading...
From: https://drive.google.com/uc?id=1dLF8lffQLgBO5Thu__Lk5Pbw57fTkncc
To: d:\AIVietNam\2024\aio-2024-hw\tests\final\23_05_2025_test1\data\final_dataset.csv

  0%|          | 0.00/220 [00:00<?, ?B/s]
100%|██████████| 220/220 [00:00<?, ?B/s] 


In [11]:
import pandas as pd

df = pd.read_csv('data/final_dataset.csv')
X_train = df.drop(columns=['diagnosis']).values.tolist()
labels = df['diagnosis'].values.tolist()

print(f'X_train:\n{X_train}')
print(f'labels:\n{labels}')


X_train:
[[0.29, 0.18, 0.12], [0.11, 0.06, 0.17], [0.34, 0.21, 0.2], [0.26, 0.15, 0.09], [0.22, 0.09, 0.2], [0.58, 0.42, 0.47], [0.56, 0.37, 0.77], [0.48, 0.38, 0.28], [0.63, 0.49, 0.39], [0.54, 0.42, 0.43]]
labels:
['B', 'B', 'B', 'B', 'B', 'M', 'M', 'M', 'M', 'M']


In [12]:
y_train = []

for label in labels:
    if label == 'B':
        y_train.append(0)
    else:
        y_train.append(1)

print(f'y_train:\n{y_train}')


y_train:
[0, 0, 0, 0, 0, 1, 1, 1, 1, 1]


In [13]:
x = [0.25, 0.25, 0.25]

def manhattan_distance(x1, x2):
    return sum(abs(a - b) for a, b in zip(x1, x2))

for i in range(3):
    print(f'{i + 1}: {manhattan_distance(x, X_train[i])}')


1: 0.24
2: 0.41000000000000003
3: 0.18000000000000002


In [14]:
manhattan_distances = [(manhattan_distance(x, X_train[i]), y_train[i]) for i in range(len(X_train))]
manhattan_distances.sort(key = lambda x: x[0])

count_classes = [0, 0]
for i in range(7):
    count_classes[manhattan_distances[i][1]] += 1

print(f'count_classes:\n{count_classes}')



count_classes:
[5, 2]


In [18]:
# Q13
C1 = np.array([0.34, 0.21, 0.2])
C2 = np.array([0.63, 0.49, 0.39])

total_dist = 0

for vec in X_train:
    vec = np.array(vec)
    dist = np.linalg.norm(C1 - vec)
    print(f'Distance: {dist}')
    total_dist += dist

print(f'Total distance: {total_dist}')

Distance: 0.09899494936611669
Distance: 0.2762245463386627
Distance: 0.0
Distance: 0.14866068747318506
Distance: 0.16970562748477142
Distance: 0.41785164831552346
Distance: 0.6315853069855252
Distance: 0.23430749027719963
Distance: 0.44564559910314383
Distance: 0.37013511046643494
Total distance: 2.793110965810563


In [19]:
# Q14
total_dist = 0

for vec in X_train:
    vec = np.array(vec)
    dist = np.linalg.norm(C2 - vec)
    print(f'Distance: {dist}')
    total_dist += dist

print(f'Total distance: {total_dist}')

Distance: 0.5334791467339656
Distance: 0.7097182539571602
Distance: 0.44564559910314383
Distance: 0.5852349955359812
Distance: 0.6034898507845845
Distance: 0.1174734012447073
Distance: 0.4045985664828782
Distance: 0.2161018278497431
Distance: 0.0
Distance: 0.1208304597359457
Total distance: 3.7365721014281092


In [20]:
# Q15
allocation = []

for vec in X_train:
    vec = np.array(vec)
    dist1 = np.linalg.norm(C1 - vec)
    dist2 = np.linalg.norm(C2 - vec)
    if dist1 < dist2:
        allocation.append(0)
    else:
        allocation.append(1)

print(f'Allocation: {allocation}')



Allocation: [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]


In [21]:
# Q16
C1_points = []
C2_points = []

for i in range(len(X_train)):
    if allocation[i] == 0:
        C1_points.append(X_train[i])
    else:
        C2_points.append(X_train[i])

C1_points = np.array(C1_points)
C2_points = np.array(C2_points)

C1_new = np.mean(C1_points, axis=0) if len(
    C1_points) > 0 else np.zeros_like(C1)
C2_new = np.mean(C2_points, axis=0) if len(
    C2_points) > 0 else np.zeros_like(C2)

print("Tọa độ tâm cụm mới C1:", C1_new)
print("Tọa độ tâm cụm mới C2:", C2_new)


Tọa độ tâm cụm mới C1: [0.244 0.138 0.156]
Tọa độ tâm cụm mới C2: [0.558 0.416 0.468]


In [22]:
# Q17
allocation = []

for vec in X_train:
    vec = np.array(vec)
    dist1 = np.linalg.norm(C1_new - vec)
    dist2 = np.linalg.norm(C2_new - vec)
    if dist1 < dist2:
        allocation.append(0)
    else:
        allocation.append(1)

print(f'Allocation: {allocation}')

Allocation: [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]


Q 18 ->

In [24]:
train_data = {
    'Outlook': ['Sunny', 'Sunny', 'Overcast', 'Rain', 'Rain', 'Overcast', 'Sunny', 'Sunny', 'Sunny', 'Rain'],
    'Temperature': ['Cool', 'Cool', 'Mild', 'Hot', 'Hot', 'Hot', 'Mild', 'Cool', 'Hot', 'Cool'],
    'Humidity': ['High', 'High', 'High', 'Normal', 'Normal', 'Normal', 'High', 'Normal', 'High', 'Normal'],
    'Wind': ['Weak', 'Strong', 'Weak', 'Weak', 'Strong', 'Strong', 'Weak', 'Weak', 'Weak', 'Weak'],
    'PlayTennis': ['Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes']
}

test_data = {
    'Outlook': ['Sunny', 'Overcast', 'Overcast', 'Rain'],
    'Temperature': ['Cool', 'Hot', 'Mild', 'Cool'],
    'Humidity': ['Normal', 'High', 'Normal', 'High'],
    'Wind': ['Strong', 'Strong', 'Weak', 'Strong'],
    'PlayTennis': ['Yes', 'Yes', 'Yes', 'No']
}

df_train = pd.DataFrame(train_data)
df_test = pd.DataFrame(test_data)

print(df_train)
print('-'*100)
print(df_test)




    Outlook Temperature Humidity    Wind PlayTennis
0     Sunny        Cool     High    Weak        Yes
1     Sunny        Cool     High  Strong         No
2  Overcast        Mild     High    Weak        Yes
3      Rain         Hot   Normal    Weak        Yes
4      Rain         Hot   Normal  Strong         No
5  Overcast         Hot   Normal  Strong        Yes
6     Sunny        Mild     High    Weak         No
7     Sunny        Cool   Normal    Weak        Yes
8     Sunny         Hot     High    Weak         No
9      Rain        Cool   Normal    Weak        Yes
----------------------------------------------------------------------------------------------------
    Outlook Temperature Humidity    Wind PlayTennis
0     Sunny        Cool   Normal  Strong        Yes
1  Overcast         Hot     High  Strong        Yes
2  Overcast        Mild   Normal    Weak        Yes
3      Rain        Cool     High  Strong         No


In [27]:
# Q18
def calculate_entropy(df):
    unique_classes, counts = np.unique(df['PlayTennis'], return_counts=True)
    probabilities = counts / len(df)
    entropy = -np.sum(probabilities * np.log2(probabilities))
    return entropy

print(calculate_entropy(df_train))



0.9709505944546686


In [28]:
# Q19
def calculate_information_gain(df, attribute):
    unique_values = np.unique(df[attribute])
    total_entropy = calculate_entropy(df)
    weighted_entropy = 0
    total_samples = len(df)
    
    for value in unique_values:
        subset = df[df[attribute] == value]
        weighted_entropy += len(subset) / total_samples * calculate_entropy(subset)
        
    return total_entropy - weighted_entropy

print(calculate_information_gain(df_train, 'Temperature'))


# Q20



0.0464393446710154


In [29]:
# Q20
def find_best_split_feature(data, features):
    gains = {}
    for feature in features:
        gain = calculate_information_gain(data, feature)
        gains[feature] = gain
        print(f"Information Gain của {feature}: {gain}")

    # Tìm thuộc tính có gain cao nhất
    best_feature = max(gains.items(), key=lambda x: x[1])
    return best_feature


# Các thuộc tính cần xem xét
features = ['Outlook', 'Temperature', 'Humidity', 'Wind']

# Tìm thuộc tính tốt nhất để split
best_feature = find_best_split_feature(df_train, features)
print(
    f"\nThuộc tính tốt nhất để chia nhánh đầu tiên là {best_feature[0]} với Information Gain = {best_feature[1]}")

Information Gain của Outlook: 0.2099865470109874
Information Gain của Temperature: 0.0464393446710154
Information Gain của Humidity: 0.12451124978365313
Information Gain của Wind: 0.0912774462416801

Thuộc tính tốt nhất để chia nhánh đầu tiên là Outlook với Information Gain = 0.2099865470109874


In [30]:
def build_decision_tree(data, features, parent_entropy=None, depth=0):
    # Nếu tất cả các mẫu thuộc cùng một class
    if len(data['PlayTennis'].unique()) == 1:
        return {'leaf': True, 'class': data['PlayTennis'].iloc[0]}

    # Nếu không còn feature nào để split
    if len(features) == 0:
        majority_class = data['PlayTennis'].mode()[0]
        return {'leaf': True, 'class': majority_class}

    # Tìm feature tốt nhất để split
    best_gain = -1
    best_feature = None

    for feature in features:
        gain = calculate_information_gain(data, feature)
        if gain > best_gain:
            best_gain = gain
            best_feature = feature

    tree = {'feature': best_feature, 'children': {}}
    remaining_features = [f for f in features if f != best_feature]

    # Chia nhánh theo các giá trị của feature tốt nhất
    for value in data[best_feature].unique():
        subset = data[data[best_feature] == value]
        if len(subset) == 0:
            tree['children'][value] = {'leaf': True, 'class': data['PlayTennis'].mode()[
                0]}
        else:
            tree['children'][value] = build_decision_tree(
                subset, remaining_features, depth=depth+1)

    return tree


features = ['Outlook', 'Temperature', 'Humidity', 'Wind']
decision_tree = build_decision_tree(df_train, features)


def count_leaves(tree):
    if tree.get('leaf', False):
        return 1
    return sum(count_leaves(child) for child in tree['children'].values())


num_leaves = count_leaves(decision_tree)
print(f"Số lá trong cây quyết định: {num_leaves}")

Số lá trong cây quyết định: 7


In [31]:
# Q22

def predict_single(tree, sample):
    """
    Dự đoán một mẫu dữ liệu dựa trên cây quyết định
    
    Args:
        tree: Cây quyết định đã xây dựng
        sample: Dictionary chứa các feature của mẫu cần dự đoán
    
    Returns:
        Kết quả dự đoán (Yes/No)
    """
    # Nếu là node lá, trả về class
    if tree.get('leaf', False):
        return tree['class']

    # Lấy giá trị của feature tại node hiện tại
    feature = tree['feature']
    value = sample[feature]

    # Nếu giá trị không có trong cây (không xuất hiện trong tập train)
    if value not in tree['children']:
        # Trả về giá trị phổ biến nhất trong node cha
        return max(tree['children'].items(), key=lambda x: len(x[1]))[1]['class']

    # Đệ quy xuống nhánh tương ứng
    return predict_single(tree['children'][value], sample)


def predict_all(tree, test_data):
    """
    Dự đoán cho toàn bộ tập test
    """
    predictions = []
    for i in range(len(test_data)):
        sample = {
            'Outlook': test_data['Outlook'][i],
            'Temperature': test_data['Temperature'][i],
            'Humidity': test_data['Humidity'][i],
            'Wind': test_data['Wind'][i]
        }
        predictions.append(predict_single(tree, sample))
    return predictions


# Dự đoán toàn bộ tập test
all_predictions = predict_all(decision_tree, df_test)
print("\nKết quả dự đoán toàn bộ tập test:")
for i, (pred, actual) in enumerate(zip(all_predictions, df_test['PlayTennis'])):
    print(f"Mẫu {i+1}: Dự đoán = {pred}, Thực tế = {actual}")


Kết quả dự đoán toàn bộ tập test:
Mẫu 1: Dự đoán = No, Thực tế = Yes
Mẫu 2: Dự đoán = Yes, Thực tế = Yes
Mẫu 3: Dự đoán = Yes, Thực tế = Yes
Mẫu 4: Dự đoán = No, Thực tế = No


In [32]:
# Q23

test_sample = {
    'Outlook': 'Overcast',
    'Wind': 'Weak'
}

print(predict_single(decision_tree, test_sample))


Yes


In [33]:
# Q24

test_sample = {
    'Temperature': 'Hot',
    'Outlook': 'Rain'
}

print(predict_single(decision_tree, test_sample))

KeyError: 'Wind'

In [35]:
# Q24

def calculate_accuracy(predictions, actual):
    """
    Tính độ chính xác của mô hình
    
    Args:
        predictions: List các dự đoán
        actual: List các giá trị thực tế
    
    Returns:
        Độ chính xác (tỷ lệ dự đoán đúng)
    """
    correct = sum(1 for p, a in zip(predictions, actual) if p == a)
    return correct / len(actual)


# Dự đoán toàn bộ tập test
predictions = predict_all(decision_tree, df_test)
actual = df_test['PlayTennis'].tolist()

# In kết quả chi tiết
print("Chi tiết dự đoán:")
for i, (pred, act) in enumerate(zip(predictions, actual), 1):
    print(f"Mẫu {i}: Dự đoán = {pred}, Thực tế = {act}")

# Tính và in độ chính xác
accuracy = calculate_accuracy(predictions, actual)
print(f"\nĐộ chính xác trên tập kiểm tra: {accuracy:.4f}")

Chi tiết dự đoán:
Mẫu 1: Dự đoán = No, Thực tế = Yes
Mẫu 2: Dự đoán = Yes, Thực tế = Yes
Mẫu 3: Dự đoán = Yes, Thực tế = Yes
Mẫu 4: Dự đoán = No, Thực tế = No

Độ chính xác trên tập kiểm tra: 0.7500


Q27

Ý nghĩa khi Information Gain = 0:
- Entropy trước và sau khi split là như nhau
- Việc phân chia theo thuộc tính này không giảm độ không chắc chắn
- Phân phối các class trong các nhánh con giống với phân phối ban đầu

Q28 Khi so sánh với các kỹ thuật ensemble như Gradient Boosting, một lợi thế nổi bật của Random Forest, đặc biệt khi làm việc với tập dữ liệu lớn, là gì?
Việc huấn luyện các cây trong Random Forest có thể được thực hiện song song một cách hiệu quả do tính độc lập của chúng.