In [1]:
import numpy as np

In [2]:
tennis_data = np.array([['Sunny','Hot', 'High', 'Weak', 'no'],
    ['Sunny','Hot', 'High', 'Strong', 'no'],
    ['Overcast','Hot', 'High', 'Weak', 'yes'],
    ['Rain','Mild', 'High', 'Weak', 'yes'],
    ['Rain','Cool', 'Normal', 'Weak', 'yes'],
    ['Rain','Cool', 'Normal', 'Strong', 'no'],
    ['Overcast','Cool', 'Normal', 'Strong', 'yes'],
    ['Overcast','Mild', 'High', 'Weak', 'no'],
    ['Sunny','Cool', 'Normal', 'Weak', 'yes'],
    ['Rain','Mild', 'Normal', 'Weak', 'yes']
    ])

# CÂU 1:

In [3]:
y_category = ["yes", "no"]
result_tennis = np.zeros(len(y_category))
for i in range(0, len(result_tennis), 1):
    result_tennis[i] = len(np.where(tennis_data[:, 4] == y_category[i])[0])/len(tennis_data)
    
print(result_tennis)

[0.6 0.4]


In [4]:
conditional_probability = []
list_feature_category = []
for i in range(0, tennis_data.shape[1] - 1, 1):
    feature_category = np.unique(tennis_data[:, i])
    list_feature_category.append(feature_category)
    
    feature_category_conditional_probability = np.zeros((len(y_category), len(feature_category)))
    for id_y in range(0, len(y_category), 1):
        for id_feature in range(0, len(feature_category), 1):
            numerator = len(np.where((tennis_data[:, i] == feature_category[id_feature]) & (tennis_data[: , 4] == y_category[id_y]))[0])
            denominator = len(np.where(tennis_data[:, 4] == y_category[id_y])[0])
            feature_category_conditional_probability[id_y, id_feature] = numerator / denominator
    conditional_probability.append(feature_category_conditional_probability)

In [5]:
for i in range(0, len(list_feature_category), 1):
    print(f"feature catefory in each column: {list_feature_category[i]}\n Its conditional probability with yes above and no below:\n {conditional_probability[i]}\n")

feature catefory in each column: ['Overcast' 'Rain' 'Sunny']
 Its conditional probability with yes above and no below:
 [[0.33333333 0.5        0.16666667]
 [0.25       0.25       0.5       ]]

feature catefory in each column: ['Cool' 'Hot' 'Mild']
 Its conditional probability with yes above and no below:
 [[0.5        0.16666667 0.33333333]
 [0.25       0.5        0.25      ]]

feature catefory in each column: ['High' 'Normal']
 Its conditional probability with yes above and no below:
 [[0.33333333 0.66666667]
 [0.75       0.25      ]]

feature catefory in each column: ['Strong' 'Weak']
 Its conditional probability with yes above and no below:
 [[0.16666667 0.83333333]
 [0.5        0.5       ]]



# CÂU 2:

In [6]:
p_X_c = conditional_probability[0][0][2] * conditional_probability[1][0][0] * conditional_probability[2][0][0] * conditional_probability[3][0][0]
p_c_X = p_X_c * result_tennis[0]
print(p_c_X)

0.0027777777777777775


# CÂU 3:

In [7]:
p_X_c = conditional_probability[0][1][2] * conditional_probability[1][1][0] * conditional_probability[2][1][0] * conditional_probability[3][1][0]
p_c_X = p_X_c * result_tennis[1]
print(p_c_X)

0.018750000000000003


-----------------------------------------------------------------------

In [8]:
traffic_data = np.array([
    ["Weekday", "Spring", "None", "None", "On Time"],
    ["Weekday", "Winter", "None", "Slight", "On Time"],
    ["Weekday", "Winter", "None", "None", "On Time"],
    ["Holiday", "Winter", "High", "slight", "Late"],
    ["Saturday", "Summer", "Normal", "None", "On Time"],
    ["Weekday", "Autumn", "Normal", "None", "Very Late"],
    ["Holiday", "Summer", "High", "Slight", "On Time"],
    ["Sunday", "Summer", "Normal", "None", "On Time"],
    ["Weekday", "Winter", "High", "Heavy", "Very Late"],
    ["Weekday", "Summer", "None", "Slight", "On Time"],
    ["Saturday", "Spring", "High", "Heavy", "Cancelled"],
    ["Weekday", "Summer", "High", "Slight", "On Time"],
    ["Weekday", "Winter", "Normal", "None", "Late"],
    ["Weekday", "Summer", "High", "None", "On Time"],
    ["Weekday", "Winter", "Normal", "Heavy", "Very Late"],
    ["Saturday", "Autumn", "High", "Slight", "On Time"],
    ["Weekday", "Autumn", "None", "Heavy", "On Time"],
    ["Holiday", "Spring", "Normal", "Slight", "On Time"],
    ["Weekday", "Spring", "Normal", "None", "On Time"],
    ["Weekday", "Spring", "Normal", "Heavy", "On Time"]
])

# CÂU 5

In [9]:
def calculate_y_probability(data):
    y_category = np.unique(data[:, data.shape[1] - 1])
    y_probability = np.zeros(len(y_category))
    for i in range(0, len(y_probability), 1):
        y_probability[i] = len(np.where(data[:, data.shape[1] - 1] == y_category[i])[0])/len(data)
    
    return y_category, y_probability

In [10]:
y_category, y_probability = calculate_y_probability(traffic_data)
for i in range(0, len(y_probability), 1):
    print(f"class: {y_category[i]} has probablity: {y_probability[i]}")

class: Cancelled has probablity: 0.05
class: Late has probablity: 0.1
class: On Time has probablity: 0.7
class: Very Late has probablity: 0.15


In [11]:
def calculate_condition_probability(data):
    y_category = np.unique(data[:, data.shape[1] - 1])
    conditional_probability = []
    list_feature_category = []
    for i in range(0, data.shape[1] - 1, 1):
        feature_category = np.unique(data[:, i])
        list_feature_category.append(feature_category)
        
        feature_category_conditional_probability = np.zeros((len(y_category), len(feature_category)))
        for id_y in range(0, len(y_category), 1):
            for id_feature in range(0, len(feature_category), 1):
                numerator = len(np.where((data[:, i] == feature_category[id_feature]) & (data[: , data.shape[1] - 1] == y_category[id_y]))[0])
                denominator = len(np.where(data[:, data.shape[1] - 1] == y_category[id_y])[0])
                feature_category_conditional_probability[id_y, id_feature] = numerator / denominator
        conditional_probability.append(feature_category_conditional_probability)
        
    return list_feature_category, conditional_probability

In [12]:
list_feature_category, conditional_probability = calculate_condition_probability(traffic_data)
for i in range(0, len(list_feature_category), 1):
    print(f"feature catefory in each column: {list_feature_category[i]}\n Its conditional probability respectively:\n {conditional_probability[i]}\n")

feature catefory in each column: ['Holiday' 'Saturday' 'Sunday' 'Weekday']
 Its conditional probability respectively:
 [[0.         1.         0.         0.        ]
 [0.5        0.         0.         0.5       ]
 [0.14285714 0.14285714 0.07142857 0.64285714]
 [0.         0.         0.         1.        ]]

feature catefory in each column: ['Autumn' 'Spring' 'Summer' 'Winter']
 Its conditional probability respectively:
 [[0.         1.         0.         0.        ]
 [0.         0.         0.         1.        ]
 [0.14285714 0.28571429 0.42857143 0.14285714]
 [0.33333333 0.         0.         0.66666667]]

feature catefory in each column: ['High' 'None' 'Normal']
 Its conditional probability respectively:
 [[1.         0.         0.        ]
 [0.5        0.         0.5       ]
 [0.28571429 0.35714286 0.35714286]
 [0.33333333 0.         0.66666667]]

feature catefory in each column: ['Heavy' 'None' 'Slight' 'slight']
 Its conditional probability respectively:
 [[1.         0.         0.

# CÂU 6, 7, 8, 9:

In [13]:
for i in range(0, len(y_probability), 1):
    p_X_c_2 = conditional_probability[0][i][3] * conditional_probability[1][i][3] * conditional_probability[2][i][0] * conditional_probability[3][i][0]
    p_c = y_probability[i]
    result = p_X_c_2 * p_c
    print(f"class: {y_category[i]} has conditional probablity: {result}")

class: Cancelled has conditional probablity: 0.0
class: Late has conditional probablity: 0.0
class: On Time has conditional probablity: 0.0026239067055393583
class: Very Late has conditional probablity: 0.02222222222222222


----------------------------------------------

In [14]:
iris_data = np.array([
    [1.4, 1.0, 1.3, 1.9, 2.0, 1.8, 3.0, 3.8, 4.1, 3.9, 4.2, 3.4],
    [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1]
])

In [15]:
y_category = np.unique(iris_data[1, :])
print(y_category)

[0. 1.]


# CÂU 11

In [16]:
mean_iris_0 = np.mean(iris_data[0][np.where(iris_data[1, :] == y_category[0])])
print(mean_iris_0)
var_iris_0 = np.var(iris_data[0][np.where(iris_data[1, :] == y_category[0])])
print(var_iris_0)

1.5666666666666667
0.1288888888888889


# CÂU 12

In [17]:
mean_iris_1 = np.mean(iris_data[0][np.where(iris_data[1, :] == y_category[1])])
print(mean_iris_1)
var_iris_1 = np.var(iris_data[0][np.where(iris_data[1, :] == y_category[1])])
print(var_iris_1)

3.733333333333333
0.1722222222222222


# CÂU 13

In [18]:
iris_datga_transpose = iris_data.T

In [19]:
def calculate_y_probability(data):
    y_category = np.unique(data[:, data.shape[1] - 1])
    y_probability = np.zeros(len(y_category))
    for i in range(0, len(y_probability), 1):
        y_probability[i] = len(np.where(data[:, data.shape[1] - 1] == y_category[i])[0])/len(data)
    
    return y_category, y_probability

In [20]:
y_category, y_probability = calculate_y_probability(iris_datga_transpose)
for i in range(0, len(y_probability), 1):
    print(f"class: {y_category[i]} has probablity: {y_probability[i]}")

class: 0.0 has probablity: 0.5
class: 1.0 has probablity: 0.5


In [21]:
def gaussian_probability(x, mean, variance):
    exponent = np.exp(-((x - mean)**2 / (2 * variance)))
    return (1 / (np.sqrt(2 * np.pi * variance))) * exponent

In [22]:
x = np.array([3.4])
prob_class_0 = gaussian_probability(x, mean_iris_0, var_iris_0) * y_probability[0]
prob_class_1 = gaussian_probability(x, mean_iris_1, var_iris_1) * y_probability[1]


print("P(Class=0|X=3.4):", prob_class_0)
print("P(Class=1|X=3.4):", prob_class_1)

P(Class=0|X=3.4): [1.20808206e-06]
P(Class=1|X=3.4): [0.34812922]
